//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string ExceptionMessage { get; set; }
        public string UserName { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
